import { defineConfig } from 'wxt';

export default defineConfig({
  // Wire in the React module — handles JSX transform and React types automatically
  modules: ['@wxt-dev/module-react'],
  manifest: {
    name: 'Photo Extractor',
    // CWS description limit is 132 chars. This is 34 chars — well within limit.
    description: 'Save photos with structured names.',
    // downloads: needed to call chrome.downloads.download() and search()
    // storage: needed for chrome.storage.session (SW keepalive) and future preferences
    permissions: ['downloads', 'storage'],
    // Icon sizes required by Chrome Web Store: 16, 32, 48, 128.
    // Generated by scripts/generate-icons.js (blue camera design on #2563EB background).
    icons: {
      16: '/icon-16.png',
      32: '/icon-32.png',
      48: '/icon-48.png',
      128: '/icon-128.png',
    },
  },
});
